{"name": "test_error_handling_example", "status": "failed", "statusDetails": {"message": "AssertionError: 应该拒绝无效的数据源配置\nassert not True", "trace": "testcase\\test_data_source_switcher_example.py:191: in test_error_handling_example\n    assert not success, \"应该拒绝无效的数据源配置\"\nE   AssertionError: 应该拒绝无效的数据源配置\nE   assert not True"}, "description": "错误处理示例", "steps": [{"name": "测试设置: TestDataSourceSwitcherExample.test_error_handling_example", "status": "passed", "start": 1754271477129, "stop": 1754271477130}, {"name": "测试清理: TestDataSourceSwitcherExample.test_error_handling_example", "status": "passed", "start": 1754271477149, "stop": 1754271477150}], "attachments": [{"name": "测试异常", "source": "5b86c369-cba4-4296-8b50-15b697aa306d-attachment.json", "type": "application/json"}, {"name": "异常堆栈", "source": "59faef32-e8fe-410d-84d9-cc2cfd57c1ac-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "34f332f9-d4fa-4f16-a08e-a1d085b538c9-attachment.txt", "type": "text/plain"}], "start": 1754271477131, "stop": 1754271477133, "uuid": "08591a25-0bb2-49f6-bbd3-91fcbce1c091", "historyId": "53b9d895e68f29e6c6abb977a0290cf4", "testCaseId": "53b9d895e68f29e6c6abb977a0290cf4", "fullName": "testcase.test_data_source_switcher_example.TestDataSourceSwitcherExample#test_error_handling_example", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_data_source_switcher_example"}, {"name": "subSuite", "value": "TestDataSourceSwitcherExample"}, {"name": "host", "value": "lihaojie"}, {"name": "thread", "value": "89128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_data_source_switcher_example"}], "titlePath": ["testcase", "test_data_source_switcher_example.py", "TestDataSourceSwitcherExample"]}