[<TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\runner.py:341>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\runner.py:242>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_hooks.py:513>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_manager.py:120>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:182>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_result.py:100>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\threadexception.py:92>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\threadexception.py:68>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\unraisableexception.py:95>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\unraisableexception.py:70>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\logging.py:846>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\logging.py:829>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\capture.py:898>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\skipping.py:257>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:103>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\runner.py:174>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\python.py:1627>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_hooks.py:513>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_manager.py:120>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:139>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:103>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\python.py:159>, <TracebackEntry C:\Users\sy_li\bgtest\utils\allure_decorators.py:31>, <TracebackEntry C:\Users\sy_li\bgtest\utils\test_decorators.py:29>, <TracebackEntry C:\Users\sy_li\bgtest\utils\test_decorators.py:300>, <TracebackEntry C:\Users\sy_li\bgtest\testcase\test_chat_gateway_optimized.py:63>, <TracebackEntry C:\Users\sy_li\bgtest\common\test_utils.py:308>, <TracebackEntry C:\Users\sy_li\bgtest\common\test_utils.py:133>]