{"name": "test_create_test_data", "status": "broken", "statusDetails": {"message": "sqlalchemy.exc.ArgumentError: Textual SQL expression 'INSERT INTO test_table (n...' should be explicitly declared as text('INSERT INTO test_table (n...')", "trace": "testcase\\test_orm_integration.py:333: in test_create_test_data\n    result = create_test_data(db_session, 'test_table', test_data)\nutils\\orm_fixtures.py:253: in create_test_data\n    result = session.execute(sql, data)\n.venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py:2365: in execute\n    return self._execute_internal(\n.venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py:2149: in _execute_internal\n    statement = coercions.expect(roles.StatementRole, statement)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py:395: in expect\n    resolved = impl._literal_coercion(\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py:621: in _literal_coercion\n    return self._text_coercion(element, argname, **kw)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py:614: in _text_coercion\n    return _no_text_coercion(element, argname)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py:584: in _no_text_coercion\n    raise exc_cls(\nE   sqlalchemy.exc.ArgumentError: Textual SQL expression 'INSERT INTO test_table (n...' should be explicitly declared as text('INSERT INTO test_table (n...')"}, "description": "测试创建测试数据功能", "steps": [{"name": "测试设置: TestDatabaseHelpers.test_create_test_data", "status": "passed", "start": 1754201565070, "stop": 1754201565077}, {"name": "测试用例: 创建测试数据测试", "status": "broken", "statusDetails": {"message": "sqlalchemy.exc.ArgumentError: Textual SQL expression 'INSERT INTO test_table (n...' should be explicitly declared as text('INSERT INTO test_table (n...')\n", "trace": "  File \"E:\\bgtest\\utils\\allure_decorators.py\", line 31, in wrapper\n    result = func(*args, **kwargs)\n  File \"E:\\bgtest\\utils\\test_decorators.py\", line 29, in wrapper\n    return func(*args, **kwargs)\n  File \"E:\\bgtest\\utils\\test_decorators.py\", line 286, in wrapper\n    return func(*args, **kwargs)\n  File \"E:\\bgtest\\utils\\test_decorators.py\", line 300, in wrapper\n    return func(*args, **kwargs)\n  File \"E:\\bgtest\\testcase\\test_orm_integration.py\", line 333, in test_create_test_data\n    result = create_test_data(db_session, 'test_table', test_data)\n  File \"E:\\bgtest\\utils\\orm_fixtures.py\", line 253, in create_test_data\n    result = session.execute(sql, data)\n  File \"E:\\bgtest\\.venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2365, in execute\n    return self._execute_internal(\n           ~~~~~~~~~~~~~~~~~~~~~~^\n        statement,\n        ^^^^^^^^^^\n    ...<4 lines>...\n        _add_event=_add_event,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"E:\\bgtest\\.venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2149, in _execute_internal\n    statement = coercions.expect(roles.StatementRole, statement)\n  File \"E:\\bgtest\\.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py\", line 395, in expect\n    resolved = impl._literal_coercion(\n        element, argname=argname, **kw\n    )\n  File \"E:\\bgtest\\.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py\", line 621, in _literal_coercion\n    return self._text_coercion(element, argname, **kw)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\bgtest\\.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py\", line 614, in _text_coercion\n    return _no_text_coercion(element, argname)\n  File \"E:\\bgtest\\.venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py\", line 584, in _no_text_coercion\n    raise exc_cls(\n    ...<7 lines>...\n    ) from err\n"}, "attachments": [{"name": "测试用例异常: 创建测试数据测试", "source": "fbb5de9d-405c-4a7b-bf28-0fe8ee00c527-attachment.json", "type": "application/json"}], "start": 1754201565080, "stop": 1754201565087}, {"name": "测试清理: TestDatabaseHelpers.test_create_test_data", "status": "passed", "start": 1754201565535, "stop": 1754201565542}], "attachments": [{"name": "测试异常", "source": "e2b7535e-0feb-419b-a21b-32d7165e6531-attachment.json", "type": "application/json"}, {"name": "异常堆栈", "source": "1fa0521f-ced7-41ae-b741-c49f72368158-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "f8b62d5a-57fa-43c6-8d2c-7711f768c46b-attachment.txt", "type": "text/plain"}], "start": 1754201565080, "stop": 1754201565094, "uuid": "014eab86-117d-471c-8069-f6248167dc0b", "historyId": "ce29960a0aaa49ba1b245620e4f5e5ca", "testCaseId": "ce29960a0aaa49ba1b245620e4f5e5ca", "fullName": "testcase.test_orm_integration.TestDatabaseHelpers#test_create_test_data", "labels": [{"name": "story", "value": "数据创建"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "辅助函数"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_orm_integration"}, {"name": "subSuite", "value": "TestDatabaseHelpers"}, {"name": "host", "value": "Ly0217"}, {"name": "thread", "value": "231192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_orm_integration"}], "titlePath": ["testcase", "test_orm_integration.py", "TestDatabaseHelpers"]}