{"name": "test_redis_data_source", "status": "failed", "statusDetails": {"message": "AssertionError: 设置Redis数据失败\nassert False", "trace": "testcase\\test_dynamic_data_source.py:66: in test_redis_data_source\n    assert success, \"设置Redis数据失败\"\nE   AssertionError: 设置Redis数据失败\nE   assert False"}, "description": "测试Redis数据源", "steps": [{"name": "测试设置: TestDynamicDataSource.test_redis_data_source", "status": "passed", "start": 1754139945341, "stop": 1754139945342}, {"name": "测试清理: TestDynamicDataSource.test_redis_data_source", "status": "passed", "start": 1754139945357, "stop": 1754139945359}], "attachments": [{"name": "测试异常", "source": "46282274-b1e7-4655-8d17-43bcc5c31684-attachment.json", "type": "application/json"}, {"name": "异常堆栈", "source": "e6457708-ca0f-4413-927f-63c997b85bd8-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "421b198e-79c9-443e-bbc3-df9d4bc8c287-attachment.txt", "type": "text/plain"}], "start": 1754139945342, "stop": 1754139945343, "uuid": "51740aff-bc7d-4365-9254-b430022f4fb9", "historyId": "25b41a75b94379710d240bc16fe00632", "testCaseId": "25b41a75b94379710d240bc16fe00632", "fullName": "testcase.test_dynamic_data_source.TestDynamicDataSource#test_redis_data_source", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_dynamic_data_source"}, {"name": "subSuite", "value": "TestDynamicDataSource"}, {"name": "host", "value": "Ly0217"}, {"name": "thread", "value": "190720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_dynamic_data_source"}], "titlePath": ["testcase", "test_dynamic_data_source.py", "TestDynamicDataSource"]}